//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiveTunes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LiveTunes.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to concert website.
        /// </summary>
        internal static string Detail_WebsiteLink {
            get {
                return ResourceManager.GetString("Detail_WebsiteLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to error: livetunes can&apos;t contact last.fm to find local concerts ({0}).  {1}.
        /// </summary>
        internal static string Error_ConcertService {
            get {
                return ResourceManager.GetString("Error_ConcertService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to error: can&apos;t find your location ({0}).
        /// </summary>
        internal static string Error_Location {
            get {
                return ResourceManager.GetString("Error_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to finding local concerts....
        /// </summary>
        internal static string Loading_Concerts {
            get {
                return ResourceManager.GetString("Loading_Concerts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to finding location....
        /// </summary>
        internal static string Loading_Location {
            get {
                return ResourceManager.GetString("Loading_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to we couldn&apos;t find any local concerts by artists you listen to. click the view artists button to tell us about more of your favorite artists.
        /// </summary>
        internal static string Notify_NoMyConcerts {
            get {
                return ResourceManager.GetString("Notify_NoMyConcerts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to there are no concerts scheduled tonight in your area.
        /// </summary>
        internal static string Notify_NoTonightConcerts {
            get {
                return ResourceManager.GetString("Notify_NoTonightConcerts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kilometers.
        /// </summary>
        internal static string Units_Kilometer {
            get {
                return ResourceManager.GetString("Units_Kilometer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to miles.
        /// </summary>
        internal static string Units_Miles {
            get {
                return ResourceManager.GetString("Units_Miles", resourceCulture);
            }
        }
    }
}
